version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flightboard-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/flightboard.db
      - CORS__AllowedOrigins=http://localhost:3000
    volumes:
      # Persist SQLite database
      - ./data:/app/data
    networks:
      - flightboard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flightboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - flightboard-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SIGNALR_URL=http://localhost:5000/flighthub

networks:
  flightboard-network:
    driver: bridge

volumes:
  flightboard-data:
    driver: local